name: ofa-gpu

channels:
  - pytorch
dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit=10.1
  - pip:
    - numpy
    - torch==1.8.1
    - torchaudio==0.8.1
    - torchvision==0.9.1
    - torchsummary
    - filelock
    - PyYaml
    - tqdm
    - thop
    - -e .
